from django.shortcuts import redirect, render
from .models import Stock
import csv
from django.contrib import messages
from .forms import CSVUploadForm

def stock_list(request):
    stocks = Stock.objects.filter(EV_EBITDA=10)
    return render(request, 'stocks/stock_list.html', {'stocks': stocks})

def index(request):
    stocks = Stock.objects.all()
    return render(request, 'stocks/index.html', {'stocks': stocks})

def load_data(request):
    # Logic to load data
    return redirect('index')

def apply_filter(request):
    # Logic to apply filter
    return redirect('index')

def upload_csv(request):
    if request.method == 'POST':
        form = CSVUploadForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = request.FILES['csv_file']
            decoded_file = csv_file.read().decode('utf-8').splitlines()
            reader = csv.DictReader(decoded_file)
            
            for row in reader:
                stock, created = Stock.objects.update_or_create(
                    symbol=row['Symbol'],
                    defaults={
                        'Paid_up': float(row['Paid-up(ล้านบาท)']),
                        'MarketCap': float(row['MarketCap(ล้านบาท)']),
                        'EV ': float(row['EV(ล้านบาท)']),
                        'EBITDA ': float(row['EBITDA(ล้านบาท)']),
                        'EV_EBITDA ': float(row['EV/EBITDA']),
                        'Price ': float(row['Price(บาท)']),
                        'P_E ': float(row['P/E(X)']),
                        'P_BV ': float(row['P/BV(X)']),
                        'Cash_YE2021 ': float(row['เงินสดและรายการเทียบเท่าเงินสด งบปี 2564']),
                        'Cash_YE2022 ': float(row['เงินสดและรายการเทียบเท่าเงินสด งบปี 2565']),
                        'Cash_YE2023 ': float(row['เงินสดและรายการเทียบเท่าเงินสด งบปี 2566']),
                        'Cash_Q12023 ': float(row['เงินสดและรายการเทียบเท่าเงินสด ไตรมาส 1/2566']),
                        'Cash_Q12024 ': float(row['เงินสดและรายการเทียบเท่าเงินสด ไตรมาส 1/2567']),
                        'A_R_Net_YE2021 ': float(row['ลูกหนี้และตั๋วเงินรับการค้าสุทธิ งบปี 2564']),
                        'A_R_Net_YE2022 ': float(row['ลูกหนี้และตั๋วเงินรับการค้าสุทธิ งบปี 2565']),
                        'A_R_Net_YE2023 ': float(row['ลูกหนี้และตั๋วเงินรับการค้าสุทธิ งบปี 2566']),
                        'A_R_Net_Q12023 ': float(row['ลูกหนี้และตั๋วเงินรับการค้าสุทธิ ไตรมาส 1/2566']),
                        'A_R_Net_Q12024 ': float(row['ลูกหนี้และตั๋วเงินรับการค้าสุทธิ ไตรมาส 1/2567']),
                        'Inventories_YE2021 ': float(row['สินค้าคงเหลือ งบปี 2564']),
                        'Inventories_YE2022 ': float(row['สินค้าคงเหลือ งบปี 2565']),
                        'Inventories_YE2023 ': float(row['สินค้าคงเหลือ งบปี 2566']),
                        'Inventories_Q12023 ': float(row['สินค้าคงเหลือ ไตรมาส 1/2566']),
                        'Inventories_Q12024 ': float(row['สินค้าคงเหลือ ไตรมาส 1/2567']),
                        'Current_Assets_YE2021 ': float(row['รวมสินทรัพย์หมุนเวียน งบปี 2564']),
                        'Current_Assets_YE2022 ': float(row['รวมสินทรัพย์หมุนเวียน งบปี 2565']),
                        'Current_Assets_YE2023 ': float(row['รวมสินทรัพย์หมุนเวียน งบปี 2566']),
                        'Current_Assets_Q12023 ': float(row['รวมสินทรัพย์หมุนเวียน ไตรมาส 1/2566']),
                        'Current_Assets_Q12024 ': float(row['รวมสินทรัพย์หมุนเวียน ไตรมาส 1/2567']),
                        'PP_E_Net_YE2021 ': float(row['ที่ดินอาคารและอุปกรณ์สุทธิ งบปี 2564']),
                        'PP_E_Net_YE2022 ': float(row['ที่ดินอาคารและอุปกรณ์สุทธิ งบปี 2565']),
                        'PP_E_Net_YE2023 ': float(row['ที่ดินอาคารและอุปกรณ์สุทธิ งบปี 2566']),
                        'PP_E_Net_Q12023 ': float(row['ที่ดินอาคารและอุปกรณ์สุทธิ ไตรมาส 1/2566']),
                        'PP_E_Net_Q12024 ': float(row['ที่ดินอาคารและอุปกรณ์สุทธิ ไตรมาส 1/2567']),
                        'Non_Current_Assets_YE2021 ': float(row['รวมสินทรัพย์ไม่หมุนเวียน งบปี 2564']),
                        'Non_Current_Assets_YE2022 ': float(row['รวมสินทรัพย์ไม่หมุนเวียน งบปี 2565']),
                        'Non_Current_Assets_YE2023 ': float(row['รวมสินทรัพย์ไม่หมุนเวียน งบปี 2566']),
                        'Non_Current_Assets_Q12023 ': float(row['รวมสินทรัพย์ไม่หมุนเวียน ไตรมาส 1/2566']),
                        'Non_Current_Assets_Q12024 ': float(row['รวมสินทรัพย์ไม่หมุนเวียน ไตรมาส 1/2567']),
                        'Total_Assets_YE2021 ': float(row['รวมสินทรัพย์ งบปี 2564']),
                        'Total_Assets_YE2022 ': float(row['รวมสินทรัพย์ งบปี 2565']),
                        'Total_Assets_YE2023 ': float(row['รวมสินทรัพย์ งบปี 2566']),
                        'Total_Assets_Q12023 ': float(row['รวมสินทรัพย์ ไตรมาส 1/2566']),
                        'Total_Assets_Q12024 ': float(row['รวมสินทรัพย์ ไตรมาส 1/2567']),
                        'O_D_YE2021 ': float(row['เงินเบิกเกินบัญชีและเงินกู้ยืม งบปี 2564']),
                        'O_D_YE2022 ': float(row['เงินเบิกเกินบัญชีและเงินกู้ยืม งบปี 2565']),
                        'O_D_YE2023 ': float(row['เงินเบิกเกินบัญชีและเงินกู้ยืม งบปี 2566']),
                        'O_D_Q12023 ': float(row['เงินเบิกเกินบัญชีและเงินกู้ยืม ไตรมาส 1/2566']),
                        'O_D_Q12024 ': float(row['เงินเบิกเกินบัญชีและเงินกู้ยืม ไตรมาส 1/2567']),
                        'A_P_Net_YE2021 ': float(row['เจ้าหนี้และตั๋วเงินจ่ายการค้าสุทธิ งบปี 2564']),
                        'A_P_Net_YE2022 ': float(row['เจ้าหนี้และตั๋วเงินจ่ายการค้าสุทธิ งบปี 2565']),
                        'A_P_Net_YE2023 ': float(row['เจ้าหนี้และตั๋วเงินจ่ายการค้าสุทธิ งบปี 2566']),
                        'A_P_Net_Q12023 ': float(row['เจ้าหนี้และตั๋วเงินจ่ายการค้าสุทธิ ไตรมาส 1/2566']),
                        'A_P_Net_Q12024 ': float(row['เจ้าหนี้และตั๋วเงินจ่ายการค้าสุทธิ ไตรมาส 1/2567']),
                        'Current_portion_LT_YE2021 ': float(row['หนี้สินระยะยาวที่ถึงกำหนดชำระภายในหนึ่งปี งบปี 2564']),
                        'Current_portion_LT_YE2022 ': float(row['หนี้สินระยะยาวที่ถึงกำหนดชำระภายในหนึ่งปี งบปี 2565']),
                        'Current_portion_LT_YE2023 ': float(row['หนี้สินระยะยาวที่ถึงกำหนดชำระภายในหนึ่งปี งบปี 2566']),
                        'Current_portion_LT_Q12023 ': float(row['หนี้สินระยะยาวที่ถึงกำหนดชำระภายในหนึ่งปี ไตรมาส 1/2566']),
                        'Current_portion_LT_Q12024 ': float(row['หนี้สินระยะยาวที่ถึงกำหนดชำระภายในหนึ่งปี ไตรมาส 1/2567']),
                        'Current_Liabilities_YE2021 ': float(row['รวมหนี้สินหมุนเวียน งบปี 2564']),
                        'Current_Liabilities_YE2022 ': float(row['รวมหนี้สินหมุนเวียน งบปี 2565']),
                        'Current_Liabilities_YE2023 ': float(row['รวมหนี้สินหมุนเวียน งบปี 2566']),
                        'Current_Liabilities_Q12023 ': float(row['รวมหนี้สินหมุนเวียน ไตรมาส 1/2566']),
                        'Current_Liabilities_Q12024 ': float(row['รวมหนี้สินหมุนเวียน ไตรมาส 1/2567']),
                        'Non_Current_Liabilities_YE2021 ': float(row['รวมหนี้สินไม่หมุนเวียน งบปี 2564']),
                        'Non_Current_Liabilities_YE2022 ': float(row['รวมหนี้สินไม่หมุนเวียน งบปี 2565']),
                        'Non_Current_Liabilities_YE2023 ': float(row['รวมหนี้สินไม่หมุนเวียน งบปี 2566']),
                        'Non_Current_Liabilities_Q12023 ': float(row['รวมหนี้สินไม่หมุนเวียน ไตรมาส 1/2566']),
                        'Non_Current_Liabilities_Q12024 ': float(row['รวมหนี้สินไม่หมุนเวียน ไตรมาส 1/2567']),
                        'Total_Liabilities_YE2021 ': float(row['รวมหนี้สิน งบปี 2564']),
                        'Total_Liabilities_YE2022 ': float(row['รวมหนี้สิน งบปี 2565']),
                        'Total_Liabilities_YE2023 ': float(row['รวมหนี้สิน งบปี 2566']),
                        'Total_Liabilities_Q12023 ': float(row['รวมหนี้สิน ไตรมาส 1/2566']),
                        'Total_Liabilities_Q12024 ': float(row['รวมหนี้สิน ไตรมาส 1/2567']),
                        'Authorized_Capital_YE2021 ': float(row['ทุนจดทะเบียน งบปี 2564']),
                        'Authorized_Capital_YE2022 ': float(row['ทุนจดทะเบียน งบปี 2565']),
                        'Authorized_Capital_YE2023 ': float(row['ทุนจดทะเบียน งบปี 2566']),
                        'Authorized_Capital_Q12023 ': float(row['ทุนจดทะเบียน ไตรมาส 1/2566']),
                        'Authorized_Capital_Q12024 ': float(row['ทุนจดทะเบียน ไตรมาส 1/2567']),
                        'Paid_up_Capital_YE2021 ': float(row['ทุนที่ออกและชำระเต็มมูลค่า งบปี 2564']),
                        'Paid_up_Capital_YE2022 ': float(row['ทุนที่ออกและชำระเต็มมูลค่า งบปี 2565']),
                        'Paid_up_Capital_YE2023 ': float(row['ทุนที่ออกและชำระเต็มมูลค่า งบปี 2566']),
                        'Paid_up_Capital_Q12023 ': float(row['ทุนที่ออกและชำระเต็มมูลค่า ไตรมาส 1/2566']),
                        'Paid_up_Capital_Q12024 ': float(row['ทุนที่ออกและชำระเต็มมูลค่า ไตรมาส 1/2567']),
                        'Premium_Share_Capital_YE2021 ': float(row['ส่วนเกิน(ต่ำกว่า)มูลค่าหุ้น งบปี 2564']),
                        'Premium_Share_Capital_YE2022 ': float(row['ส่วนเกิน(ต่ำกว่า)มูลค่าหุ้น งบปี 2565']),
                        'Premium_Share_Capital_YE2023 ': float(row['ส่วนเกิน(ต่ำกว่า)มูลค่าหุ้น งบปี 2566']),
                        'Premium_Share_Capital_Q12023 ': float(row['ส่วนเกิน(ต่ำกว่า)มูลค่าหุ้น ไตรมาส 1/2566']),
                        'Premium_Share_Capital_Q12024 ': float(row['ส่วนเกิน(ต่ำกว่า)มูลค่าหุ้น ไตรมาส 1/2567']),
                        'Retained_Earnings_YE2021 ': float(row['กำไร(ขาดทุน)สะสม งบปี 2564']),
                        'Retained_Earnings_YE2022 ': float(row['กำไร(ขาดทุน)สะสม งบปี 2565']),
                        'Retained_Earnings_YE2023 ': float(row['กำไร(ขาดทุน)สะสม งบปี 2566']),
                        'Retained_Earnings_Q12023 ': float(row['กำไร(ขาดทุน)สะสม ไตรมาส 1/2566']),
                        'Retained_Earnings_Q12024 ': float(row['กำไร(ขาดทุน)สะสม ไตรมาส 1/2567']),
                        'Treasury_Stock_YE2021 ': float(row['หุ้นทุนรับซื้อคืน งบปี 2564']),
                        'Treasury_Stock_YE2022 ': float(row['หุ้นทุนรับซื้อคืน งบปี 2565']),
                        'Treasury_Stock_YE2023 ': float(row['หุ้นทุนรับซื้อคืน งบปี 2566']),
                        'Treasury_Stock_Q12023 ': float(row['หุ้นทุนรับซื้อคืน ไตรมาส 1/2566']),
                        'Treasury_Stock_Q12024 ': float(row['หุ้นทุนรับซื้อคืน ไตรมาส 1/2567']),
                        'Share_Company_Subsidiaries_YE2021 ': float(row['หุ้นที่ถือโดยบริษัทย่อย งบปี 2564']),
                        'Share_Company_Subsidiaries_YE2022 ': float(row['หุ้นที่ถือโดยบริษัทย่อย งบปี 2565']),
                        'Share_Company_Subsidiaries_YE2023 ': float(row['หุ้นที่ถือโดยบริษัทย่อย งบปี 2566']),
                        'Share_Company_Subsidiaries_Q12023 ': float(row['หุ้นที่ถือโดยบริษัทย่อย ไตรมาส 1/2566']),
                        'Share_Company_Subsidiaries_Q12024 ': float(row['หุ้นที่ถือโดยบริษัทย่อย ไตรมาส 1/2567']),
                        'Other_Component_Equity_YE2021 ': float(row['องค์ประกอบอื่นของส่วนของผู้ถือหุ้น งบปี 2564']),
                        'Other_Component_Equity_YE2022 ': float(row['องค์ประกอบอื่นของส่วนของผู้ถือหุ้น งบปี 2565']),
                        'Other_Component_Equity_YE2023 ': float(row['องค์ประกอบอื่นของส่วนของผู้ถือหุ้น งบปี 2566']),
                        'Other_Component_Equity_Q12023 ': float(row['องค์ประกอบอื่นของส่วนของผู้ถือหุ้น ไตรมาส 1/2566']),
                        'Other_Component_Equity_Q12024 ': float(row['องค์ประกอบอื่นของส่วนของผู้ถือหุ้น ไตรมาส 1/2567']),
                        'Surplus_YE2021 ': float(row['- ส่วนเกิน (ต่ำกว่า) ทุน งบปี 2564']),
                        'Surplus_YE2022 ': float(row['- ส่วนเกิน (ต่ำกว่า) ทุน งบปี 2565']),
                        'Surplus_YE2023 ': float(row['- ส่วนเกิน (ต่ำกว่า) ทุน งบปี 2566']),
                        'Surplus_Q12023 ': float(row['- ส่วนเกิน (ต่ำกว่า) ทุน ไตรมาส 1/2566']),
                        'Surplus_Q12024 ': float(row['- ส่วนเกิน (ต่ำกว่า) ทุน ไตรมาส 1/2567']),
                        'Shareholders_Equity_YE2021 ': float(row['รวมส่วนของผู้ถือหุ้นบริษัทใหญ่ งบปี 2564']),
                        'Shareholders_Equity_YE2022 ': float(row['รวมส่วนของผู้ถือหุ้นบริษัทใหญ่ งบปี 2565']),
                        'Shareholders_Equity_YE2023 ': float(row['รวมส่วนของผู้ถือหุ้นบริษัทใหญ่ งบปี 2566']),
                        'Shareholders_Equity_Q12023 ': float(row['รวมส่วนของผู้ถือหุ้นบริษัทใหญ่ ไตรมาส 1/2566']),
                        'Shareholders_Equity_Q12024 ': float(row['รวมส่วนของผู้ถือหุ้นบริษัทใหญ่ ไตรมาส 1/2567']),
                        'Minority_Interest_YE2021 ': float(row['ส่วนของผู้ถือหุ้นส่วนน้อย งบปี 2564']),
                        'Minority_Interest_YE2022 ': float(row['ส่วนของผู้ถือหุ้นส่วนน้อย งบปี 2565']),
                        'Minority_Interest_YE2023 ': float(row['ส่วนของผู้ถือหุ้นส่วนน้อย งบปี 2566']),
                        'Minority_Interest_Q12023 ': float(row['ส่วนของผู้ถือหุ้นส่วนน้อย ไตรมาส 1/2566']),
                        'Minority_Interest_Q12024 ': float(row['ส่วนของผู้ถือหุ้นส่วนน้อย ไตรมาส 1/2567']),
                        'Revenue_From_Operations_YE2021 ': float(row['รายได้จากการดำเนินธุรกิจ งบปี 2564']),
                        'Revenue_From_Operations_YE2022 ': float(row['รายได้จากการดำเนินธุรกิจ งบปี 2565']),
                        'Revenue_From_Operations_YE2023 ': float(row['รายได้จากการดำเนินธุรกิจ งบปี 2566']),
                        'Revenue_From_Operations_Q12023 ': float(row['รายได้จากการดำเนินธุรกิจ ไตรมาส 1/2566']),
                        'Revenue_From_Operations_Q12024 ': float(row['รายได้จากการดำเนินธุรกิจ ไตรมาส 1/2567']),
                        'Other_Income_YE2021 ': float(row['รายได้อื่น งบปี 2564']),
                        'Other_Income_YE2022 ': float(row['รายได้อื่น งบปี 2565']),
                        'Other_Income_YE2023 ': float(row['รายได้อื่น งบปี 2566']),
                        'Other_Income_Q12023 ': float(row['รายได้อื่น ไตรมาส 1/2566']),
                        'Other_Income_Q12024 ': float(row['รายได้อื่น ไตรมาส 1/2567']),
                        'Total_Revenues_YE2021 ': float(row['รวมรายได้ งบปี 2564']),
                        'Total_Revenues_YE2022 ': float(row['รวมรายได้ งบปี 2565']),
                        'Total_Revenues_YE2023 ': float(row['รวมรายได้ งบปี 2566']),
                        'Total_Revenues_Q12023 ': float(row['รวมรายได้ ไตรมาส 1/2566']),
                        'Total_Revenues_Q12024 ': float(row['รวมรายได้ ไตรมาส 1/2567']),
                        'Costs_YE2021 ': float(row['ต้นทุน งบปี 2564']),
                        'Costs_YE2022 ': float(row['ต้นทุน งบปี 2565']),
                        'Costs_YE2023 ': float(row['ต้นทุน งบปี 2566']),
                        'Costs_Q12023 ': float(row['ต้นทุน ไตรมาส 1/2566']),
                        'Costs_Q12024 ': float(row['ต้นทุน ไตรมาส 1/2567']),
                        'Sell_Administrative_Expenses_YE2021 ': float(row['ค่าใช้จ่ายในการขายและบริหาร งบปี 2564']),
                        'Sell_Administrative_Expenses_YE2022 ': float(row['ค่าใช้จ่ายในการขายและบริหาร งบปี 2565']),
                        'Sell_Administrative_Expenses_YE2023 ': float(row['ค่าใช้จ่ายในการขายและบริหาร งบปี 2566']),
                        'Sell_Administrative_Expenses_Q12023 ': float(row['ค่าใช้จ่ายในการขายและบริหาร ไตรมาส 1/2566']),
                        'Sell_Administrative_Expenses_Q12024 ': float(row['ค่าใช้จ่ายในการขายและบริหาร ไตรมาส 1/2567']),
                        'Total_Cost_Expenses_YE2021 ': float(row['รวมต้นทุนและค่าใช้จ่าย งบปี 2564']),
                        'Total_Cost_Expenses_YE2022 ': float(row['รวมต้นทุนและค่าใช้จ่าย งบปี 2565']),
                        'Total_Cost_Expenses_YE2023 ': float(row['รวมต้นทุนและค่าใช้จ่าย งบปี 2566']),
                        'Total_Cost_Expenses_Q12023 ': float(row['รวมต้นทุนและค่าใช้จ่าย ไตรมาส 1/2566']),
                        'Total_Cost_Expenses_Q12024 ': float(row['รวมต้นทุนและค่าใช้จ่าย ไตรมาส 1/2567']),
                        'EBITDA_YE2021 ': float(row['EBITDA งบปี 2564']),
                        'EBITDA_YE2022 ': float(row['EBITDA งบปี 2565']),
                        'EBITDA_YE2023 ': float(row['EBITDA งบปี 2566']),
                        'EBITDA_Q12023 ': float(row['EBITDA ไตรมาส 1/2566']),
                        'EBITDA_Q12024 ': float(row['EBITDA ไตรมาส 1/2567']),
                        'Depre_Amor_YE2021 ': float(row['ค่าเสื่อมและค่าตัดจำหน่าย งบปี 2564']),
                        'Depre_Amor_YE2022 ': float(row['ค่าเสื่อมและค่าตัดจำหน่าย งบปี 2565']),
                        'Depre_Amor_YE2023 ': float(row['ค่าเสื่อมและค่าตัดจำหน่าย งบปี 2566']),
                        'Depre_Amor_Q12023 ': float(row['ค่าเสื่อมและค่าตัดจำหน่าย ไตรมาส 1/2566']),
                        'Depre_Amor_Q12024 ': float(row['ค่าเสื่อมและค่าตัดจำหน่าย ไตรมาส 1/2567']),
                        'EBIT_YE2021 ': float(row['กำไร (ขาดทุน) ก่อนต้นทุนทางการเงิน และภาษีเงินได้ งบปี 2564']),
                        'EBIT_YE2022 ': float(row['กำไร (ขาดทุน) ก่อนต้นทุนทางการเงิน และภาษีเงินได้ งบปี 2565']),
                        'EBIT_YE2023 ': float(row['กำไร (ขาดทุน) ก่อนต้นทุนทางการเงิน และภาษีเงินได้ งบปี 2566']),
                        'EBIT_Q12023 ': float(row['กำไร (ขาดทุน) ก่อนต้นทุนทางการเงิน และภาษีเงินได้ ไตรมาส 1/2566']),
                        'EBIT_Q12024 ': float(row['กำไร (ขาดทุน) ก่อนต้นทุนทางการเงิน และภาษีเงินได้ ไตรมาส 1/2567']),
                        'Net_Profit_YE2021 ': float(row['กำไร(ขาดทุน)สุทธิ : ผู้ถือหุ้นบริษัทใหญ่ งบปี 2564']),
                        'Net_Profit_YE2022 ': float(row['กำไร(ขาดทุน)สุทธิ : ผู้ถือหุ้นบริษัทใหญ่ งบปี 2565']),
                        'Net_Profit_YE2023 ': float(row['กำไร(ขาดทุน)สุทธิ : ผู้ถือหุ้นบริษัทใหญ่ งบปี 2566']),
                        'Net_Profit_Q12023 ': float(row['กำไร(ขาดทุน)สุทธิ : ผู้ถือหุ้นบริษัทใหญ่ ไตรมาส 1/2566']),
                        'Net_Profit_Q12024 ': float(row['กำไร(ขาดทุน)สุทธิ : ผู้ถือหุ้นบริษัทใหญ่ ไตรมาส 1/2567']),
                        'EPS_YE2021 ': float(row['กำไรต่อหุ้น (บาท) งบปี 2564']),
                        'EPS_YE2022 ': float(row['กำไรต่อหุ้น (บาท) งบปี 2565']),
                        'EPS_YE2023 ': float(row['กำไรต่อหุ้น (บาท) งบปี 2566']),
                        'EPS_Q12023 ': float(row['กำไรต่อหุ้น (บาท) ไตรมาส 1/2566']),
                        'EPS_Q12024 ': float(row['กำไรต่อหุ้น (บาท) ไตรมาส 1/2567']),
                        'Operating_Cash_Flow_YE2021 ': float(row['เงินสดสุทธิจากกิจกรรมดำเนินงาน งบปี 2564']),
                        'Operating_Cash_Flow_YE2022 ': float(row['เงินสดสุทธิจากกิจกรรมดำเนินงาน งบปี 2565']),
                        'Operating_Cash_Flow_YE2023 ': float(row['เงินสดสุทธิจากกิจกรรมดำเนินงาน งบปี 2566']),
                        'Operating_Cash_Flow_Q12023 ': float(row['เงินสดสุทธิจากกิจกรรมดำเนินงาน ไตรมาส 1/2566']),
                        'Operating_Cash_Flow_Q12024 ': float(row['เงินสดสุทธิจากกิจกรรมดำเนินงาน ไตรมาส 1/2567']),
                        'Investing_Cash_Flow_YE2021 ': float(row['เงินสดสุทธิจากกิจกรรมลงทุน งบปี 2564']),
                        'Investing_Cash_Flow_YE2022 ': float(row['เงินสดสุทธิจากกิจกรรมลงทุน งบปี 2565']),
                        'Investing_Cash_Flow_YE2023 ': float(row['เงินสดสุทธิจากกิจกรรมลงทุน งบปี 2566']),
                        'Investing_Cash_Flow_Q12023 ': float(row['เงินสดสุทธิจากกิจกรรมลงทุน ไตรมาส 1/2566']),
                        'Investing_Cash_Flow_Q12024 ': float(row['เงินสดสุทธิจากกิจกรรมลงทุน ไตรมาส 1/2567']),
                        'Financing_Cash_Flow_YE2021 ': float(row['เงินสดสุทธิจากกิจกรรมจัดหาเงิน งบปี 2564']),
                        'Financing_Cash_Flow_YE2022 ': float(row['เงินสดสุทธิจากกิจกรรมจัดหาเงิน งบปี 2565']),
                        'Financing_Cash_Flow_YE2023 ': float(row['เงินสดสุทธิจากกิจกรรมจัดหาเงิน งบปี 2566']),
                        'Financing_Cash_Flow_Q12023 ': float(row['เงินสดสุทธิจากกิจกรรมจัดหาเงิน ไตรมาส 1/2566']),
                        'Financing_Cash_Flow_Q12024 ': float(row['เงินสดสุทธิจากกิจกรรมจัดหาเงิน ไตรมาส 1/2567']),
                        'Net_Cash_Flow_YE2021 ': float(row['เงินสดสุทธิ งบปี 2564']),
                        'Net_Cash_Flow_YE2022 ': float(row['เงินสดสุทธิ งบปี 2565']),
                        'Net_Cash_Flow_YE2023 ': float(row['เงินสดสุทธิ งบปี 2566']),
                        'Net_Cash_Flow_Q12023 ': float(row['เงินสดสุทธิ ไตรมาส 1/2566']),
                        'Net_Cash_Flow_Q12024 ': float(row['เงินสดสุทธิ ไตรมาส 1/2567']),
                        'Current_Ratio_YE2022 ': float(row['อัตราส่วนสภาพคล่อง (เท่า) งบปี 2565']),
                        'Current_Ratio_YE2023 ': float(row['อัตราส่วนสภาพคล่อง (เท่า) งบปี 2566']),
                        'Current_Ratio_Q12023 ': float(row['อัตราส่วนสภาพคล่อง (เท่า) ไตรมาส 1/2566']),
                        'Current_Ratio_Q12024 ': float(row['อัตราส่วนสภาพคล่อง (เท่า) ไตรมาส 1/2567']),
                        'ROE_YE2022 ': float(row['อัตราผลตอบแทนผู้ถือหุ้น (%) งบปี 2565']),
                        'ROE_YE2023 ': float(row['อัตราผลตอบแทนผู้ถือหุ้น (%) งบปี 2566']),
                        'ROE_Q12023 ': float(row['อัตราผลตอบแทนผู้ถือหุ้น (%) ไตรมาส 1/2566']),
                        'ROE_Q12024 ': float(row['อัตราผลตอบแทนผู้ถือหุ้น (%) ไตรมาส 1/2567']),
                        'ROA_YE2022 ': float(row['อัตราผลตอบแทนจากสินทรัพย์ (%) งบปี 2565']),
                        'ROA_YE2023 ': float(row['อัตราผลตอบแทนจากสินทรัพย์ (%) งบปี 2566']),
                        'ROA_Q12023 ': float(row['อัตราผลตอบแทนจากสินทรัพย์ (%) ไตรมาส 1/2566']),
                        'ROA_Q12024 ': float(row['อัตราผลตอบแทนจากสินทรัพย์ (%) ไตรมาส 1/2567']),
                        'D_E_YE2022 ': float(row['อัตราส่วนหนี้สินต่อส่วนของผู้ถือหุ้น (เท่า) งบปี 2565']),
                        'D_E_YE2023 ': float(row['อัตราส่วนหนี้สินต่อส่วนของผู้ถือหุ้น (เท่า) งบปี 2566']),
                        'D_E_Q12023 ': float(row['อัตราส่วนหนี้สินต่อส่วนของผู้ถือหุ้น (เท่า) ไตรมาส 1/2566']),
                        'D_E_Q12024 ': float(row['อัตราส่วนหนี้สินต่อส่วนของผู้ถือหุ้น (เท่า) ไตรมาส 1/2567']),
                        'Total_Assets_Turnover_YE2022 ': float(row['อัตราส่วนหมุนเวียนทรัพย์สิน (เท่า) งบปี 2565']),
                        'Total_Assets_Turnover_YE2023 ': float(row['อัตราส่วนหมุนเวียนทรัพย์สิน (เท่า) งบปี 2566']),
                        'Total_Assets_Turnover_Q12023 ': float(row['อัตราส่วนหมุนเวียนทรัพย์สิน (เท่า) ไตรมาส 1/2566']),
                        'Total_Assets_Turnover_Q12024 ': float(row['อัตราส่วนหมุนเวียนทรัพย์สิน (เท่า) ไตรมาส 1/2567']),
                        'Gross_Profit_Margin_YE2022 ': float(row['อัตรากำไรขั้นต้น (%) งบปี 2565']),
                        'Gross_Profit_Margin_YE2023 ': float(row['อัตรากำไรขั้นต้น (%) งบปี 2566']),
                        'Gross_Profit_Margin_Q12023 ': float(row['อัตรากำไรขั้นต้น (%) ไตรมาส 1/2566']),
                        'Gross_Profit_Margin_Q12024 ': float(row['อัตรากำไรขั้นต้น (%) ไตรมาส 1/2567']),
                        'EBIT_Margin_YE2022 ': float(row['EBIT Margin (%) งบปี 2565']),
                        'EBIT_Margin_YE2023 ': float(row['EBIT Margin (%) งบปี 2566']),
                        'EBIT_Margin_Q12023 ': float(row['EBIT Margin (%) ไตรมาส 1/2566']),
                        'EBIT_Margin_Q12024 ': float(row['EBIT Margin (%) ไตรมาส 1/2567']),
                        'Net_Profit_Margin_YE2022 ': float(row['อัตรากำไรสุทธิ (%) งบปี 2565']),
                        'Net_Profit_Margin_YE2023 ': float(row['อัตรากำไรสุทธิ (%) งบปี 2566']),
                        'Net_Profit_Margin_Q12023 ': float(row['อัตรากำไรสุทธิ (%) ไตรมาส 1/2566']),
                        'Net_Profit_Margin_Q12024 ': float(row['อัตรากำไรสุทธิ (%) ไตรมาส 1/2567']),
                        'Sales_Growth_YE2022 ': float(row['อัตราการเปลี่ยนแปลงยอดขาย งบปี 2565']),
                        'Sales_Growth_YE2023 ': float(row['อัตราการเปลี่ยนแปลงยอดขาย งบปี 2566']),
                        'Sales_Growth_Q12023 ': float(row['อัตราการเปลี่ยนแปลงยอดขาย ไตรมาส 1/2566']),
                        'Sales_Growth_Q12024 ': float(row['อัตราการเปลี่ยนแปลงยอดขาย ไตรมาส 1/2567']),
                        'COGs_Growth_YE2022 ': float(row['อัตราการเปลี่ยนแปลงต้นทุนขาย งบปี 2565']),
                        'COGs_Growth_YE2023 ': float(row['อัตราการเปลี่ยนแปลงต้นทุนขาย งบปี 2566']),
                        'COGs_Growth_Q12023 ': float(row['อัตราการเปลี่ยนแปลงต้นทุนขาย ไตรมาส 1/2566']),
                        'COGs_Growth_Q12024 ': float(row['อัตราการเปลี่ยนแปลงต้นทุนขาย ไตรมาส 1/2567']),
                        'Total_Revenue_Growth_YE2022 ': float(row['อัตราการเปลี่ยนแปลงรายได้รวม งบปี 2565']),
                        'Total_Revenue_Growth_YE2023 ': float(row['อัตราการเปลี่ยนแปลงรายได้รวม งบปี 2566']),
                        'Total_Revenue_Growth_Q12023 ': float(row['อัตราการเปลี่ยนแปลงรายได้รวม ไตรมาส 1/2566']),
                        'Total_Revenue_Growth_Q12024 ': float(row['อัตราการเปลี่ยนแปลงรายได้รวม ไตรมาส 1/2567']),
                        'Total_Expense_Growth_YE2022 ': float(row['อัตราการเปลี่ยนแปลงค่าใช้จ่ายรวม งบปี 2565']),
                        'Total_Expense_Growth_YE2023 ': float(row['อัตราการเปลี่ยนแปลงค่าใช้จ่ายรวม งบปี 2566']),
                        'Total_Expense_Growth_Q12023 ': float(row['อัตราการเปลี่ยนแปลงค่าใช้จ่ายรวม ไตรมาส 1/2566']),
                        'Total_Expense_Growth_Q12024 ': float(row['อัตราการเปลี่ยนแปลงค่าใช้จ่ายรวม ไตรมาส 1/2567']),
                        'Net_Profit_Growth_YE2022 ': float(row['อัตราการเปลี่ยนแปลงกำไรสุทธิ งบปี 2565']),
                        'Net_Profit_Growth_YE2023 ': float(row['อัตราการเปลี่ยนแปลงกำไรสุทธิ งบปี 2566']),
                        'Net_Profit_Growth_Q12023 ': float(row['อัตราการเปลี่ยนแปลงกำไรสุทธิ ไตรมาส 1/2566']),
                        'Net_Profit_Growth_Q12024 ': float(row['อัตราการเปลี่ยนแปลงกำไรสุทธิ ไตรมาส 1/2567']),
                        'A_R_Turnover_Times_YE2022 ': float(row['อัตราส่วนหมุนเวียนลูกหนี้การค้า (เท่า) งบปี 2565']),
                        'A_R_Turnover_Times_YE2023 ': float(row['อัตราส่วนหมุนเวียนลูกหนี้การค้า (เท่า) งบปี 2566']),
                        'A_R_Turnover_Times_Q12023 ': float(row['อัตราส่วนหมุนเวียนลูกหนี้การค้า (เท่า) ไตรมาส 1/2566']),
                        'A_R_Turnover_Times_Q12024 ': float(row['อัตราส่วนหมุนเวียนลูกหนี้การค้า (เท่า) ไตรมาส 1/2567']),
                        'Avg_Collection_Period_Days_YE2022 ': float(row['ระยะเวลาเก็บหนี้เฉลี่ย (วัน) งบปี 2565']),
                        'Avg_Collection_Period_Days_YE2023 ': float(row['ระยะเวลาเก็บหนี้เฉลี่ย (วัน) งบปี 2566']),
                        'Avg_Collection_Period_Days_Q12023 ': float(row['ระยะเวลาเก็บหนี้เฉลี่ย (วัน) ไตรมาส 1/2566']),
                        'Avg_Collection_Period_Days_Q12024 ': float(row['ระยะเวลาเก็บหนี้เฉลี่ย (วัน) ไตรมาส 1/2567']),
                        'Inventory_Turnover_Times_YE2022 ': float(row['อัตราส่วนหมุนเวียนสินค้าคงเหลือ (เท่า) งบปี 2565']),
                        'Inventory_Turnover_Times_YE2023 ': float(row['อัตราส่วนหมุนเวียนสินค้าคงเหลือ (เท่า) งบปี 2566']),
                        'Inventory_Turnover_Times_Q12023 ': float(row['อัตราส่วนหมุนเวียนสินค้าคงเหลือ (เท่า) ไตรมาส 1/2566']),
                        'Inventory_Turnover_Times_Q12024 ': float(row['อัตราส่วนหมุนเวียนสินค้าคงเหลือ (เท่า) ไตรมาส 1/2567']),
                        'Avg_Inventory_Period_Days_YE2022 ': float(row['ระยะเวลาขายสินค้าเฉลี่ย (วัน) งบปี 2565']),
                        'Avg_Inventory_Period_Days_YE2023 ': float(row['ระยะเวลาขายสินค้าเฉลี่ย (วัน) งบปี 2566']),
                        'Avg_Inventory_Period_Days_Q12023 ': float(row['ระยะเวลาขายสินค้าเฉลี่ย (วัน) ไตรมาส 1/2566']),
                        'Avg_Inventory_Period_Days_Q12024 ': float(row['ระยะเวลาขายสินค้าเฉลี่ย (วัน) ไตรมาส 1/2567']),
                        'A_P_Turnover_Times_YE2022 ': float(row['อัตราส่วนหมุนเวียนเจ้าหนี้การค้า (เท่า) งบปี 2565']),
                        'A_P_Turnover_Times_YE2023 ': float(row['อัตราส่วนหมุนเวียนเจ้าหนี้การค้า (เท่า) งบปี 2566']),
                        'A_P_Turnover_Times_Q12023 ': float(row['อัตราส่วนหมุนเวียนเจ้าหนี้การค้า (เท่า) ไตรมาส 1/2566']),
                        'A_P_Turnover_Times_Q12024 ': float(row['อัตราส่วนหมุนเวียนเจ้าหนี้การค้า (เท่า) ไตรมาส 1/2567']),
                        'Avg_Payment_Period_Days_YE2022 ': float(row['ระยะเวลาชำระหนี้เจ้าหนี้การค้า (วัน) งบปี 2565']),
                        'Avg_Payment_Period_Days_YE2023 ': float(row['ระยะเวลาชำระหนี้เจ้าหนี้การค้า (วัน) งบปี 2566']),
                        'Avg_Payment_Period_Days_Q12023 ': float(row['ระยะเวลาชำระหนี้เจ้าหนี้การค้า (วัน) ไตรมาส 1/2566']),
                        'Avg_Payment_Period_Days_Q12024 ': float(row['ระยะเวลาชำระหนี้เจ้าหนี้การค้า (วัน) ไตรมาส 1/2567']),
                        'Cash_Cycle_Days_YE2022 ': float(row['วงจรเงินสด (วัน) งบปี 2565']),
                        'Cash_Cycle_Days_YE2023 ': float(row['วงจรเงินสด (วัน) งบปี 2566']),
                        'Cash_Cycle_Days_Q12023 ': float(row['วงจรเงินสด (วัน) ไตรมาส 1/2566']),
                        'Cash_Cycle_Days_Q12024 ': float(row['วงจรเงินสด (วัน) ไตรมาส 1/2567']),
                    }
                )
            
            messages.success(request, "CSV file has been uploaded and data inserted successfully.")
            return redirect('stock_list')
    else:
        form = CSVUploadForm()

    return render(request, 'stocks/upload_csv.html', {'form': form})

