from django.shortcuts import redirect, render
from .models import Stock
import csv
from django.contrib import messages
from .forms import CSVUploadForm

def stock_list(request):
    stocks = Stock.objects.filter(EV_EBITDA=10)
    return render(request, 'stocks/stock_list.html', {'stocks': stocks})

def index(request):
    stocks = Stock.objects.all()
    return render(request, 'stocks/index.html', {'stocks': stocks})

def load_data(request):
    # Logic to load data
    return redirect('index')

def apply_filter(request):
    # Logic to apply filter
    return redirect('index')

def upload_csv(request):
    if request.method == 'POST':
        form = CSVUploadForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = request.FILES['csv_file']
            decoded_file = csv_file.read().decode('utf-8').splitlines()
            reader = csv.DictReader(decoded_file)
            
            for row in reader:
                stock, created = Stock.objects.update_or_create(
                    symbol=row['Symbol'],
                    defaults={
                        'Paid_up': float(row['Paid-up(ล้านบาท)']),
                        'MarketCap': float(row['MarketCap(ล้านบาท)']),
                        'EV ': float(row['']),
                        'EBITDA ': float(row['']),
                        'EV_EBITDA ': float(row['']),
                        'Price ': float(row['']),
                        'P_E ': float(row['']),
                        'P_BV ': float(row['']),
                        'Cash_YE2021 ': float(row['']),
                        'Cash_YE2022 ': float(row['']),
                        'Cash_YE2023 ': float(row['']),
                        'Cash_Q12023 ': float(row['']),
                        'Cash_Q12024 ': float(row['']),
                        'A_R_Net_YE2021 ': float(row['']),
                        'A_R_Net_YE2022 ': float(row['']),
                        'A_R_Net_YE2023 ': float(row['']),
                        'A_R_Net_Q12023 ': float(row['']),
                        'A_R_Net_Q12024 ': float(row['']),
                        'Inventories_YE2021 ': float(row['']),
                        'Inventories_YE2022 ': float(row['']),
                        'Inventories_YE2023 ': float(row['']),
                        'Inventories_Q12023 ': float(row['']),
                        'Inventories_Q12024 ': float(row['']),
                        'Current_Assets_YE2021 ': float(row['']),
                        'Current_Assets_YE2022 ': float(row['']),
                        'Current_Assets_YE2023 ': float(row['']),
                        'Current_Assets_Q12023 ': float(row['']),
                        'Current_Assets_Q12024 ': float(row['']),
                        'PP_E_Net_YE2021 ': float(row['']),
                        'PP_E_Net_YE2022 ': float(row['']),
                        'PP_E_Net_YE2023 ': float(row['']),
                        'PP_E_Net_Q12023 ': float(row['']),
                        'PP_E_Net_Q12024 ': float(row['']),
                        'Non_Current_Assets_YE2021 ': float(row['']),
                        'Non_Current_Assets_YE2022 ': float(row['']),
                        'Non_Current_Assets_YE2023 ': float(row['']),
                        'Non_Current_Assets_Q12023 ': float(row['']),
                        'Non_Current_Assets_Q12024 ': float(row['']),
                        'Total_Assets_YE2021 ': float(row['']),
                        'Total_Assets_YE2022 ': float(row['']),
                        'Total_Assets_YE2023 ': float(row['']),
                        'Total_Assets_Q12023 ': float(row['']),
                        'Total_Assets_Q12024 ': float(row['']),
                        'O_D_YE2021 ': float(row['']),
                        'O_D_YE2022 ': float(row['']),
                        'O_D_YE2023 ': float(row['']),
                        'O_D_Q12023 ': float(row['']),
                        'O_D_Q12024 ': float(row['']),
                        'A_P_Net_YE2021 ': float(row['']),
                        'A_P_Net_YE2022 ': float(row['']),
                        'A_P_Net_YE2023 ': float(row['']),
                        'A_P_Net_Q12023 ': float(row['']),
                        'A_P_Net_Q12024 ': float(row['']),
                        'Current_portion_LT_YE2021 ': float(row['']),
                        'Current_portion_LT_YE2022 ': float(row['']),
                        'Current_portion_LT_YE2023 ': float(row['']),
                        'Current_portion_LT_Q12023 ': float(row['']),
                        'Current_portion_LT_Q12024 ': float(row['']),
                        'Current_Liabilities_YE2021 ': float(row['']),
                        'Current_Liabilities_YE2022 ': float(row['']),
                        'Current_Liabilities_YE2023 ': float(row['']),
                        'Current_Liabilities_Q12023 ': float(row['']),
                        'Current_Liabilities_Q12024 ': float(row['']),
                        'Non_Current_Liabilities_YE2021 ': float(row['']),
                        'Non_Current_Liabilities_YE2022 ': float(row['']),
                        'Non_Current_Liabilities_YE2023 ': float(row['']),
                        'Non_Current_Liabilities_Q12023 ': float(row['']),
                        'Non_Current_Liabilities_Q12024 ': float(row['']),
                        'Total_Liabilities_YE2021 ': float(row['']),
                        'Total_Liabilities_YE2022 ': float(row['']),
                        'Total_Liabilities_YE2023 ': float(row['']),
                        'Total_Liabilities_Q12023 ': float(row['']),
                        'Total_Liabilities_Q12024 ': float(row['']),
                        'Authorized_Capital_YE2021 ': float(row['']),
                        'Authorized_Capital_YE2022 ': float(row['']),
                        'Authorized_Capital_YE2023 ': float(row['']),
                        'Authorized_Capital_Q12023 ': float(row['']),
                        'Authorized_Capital_Q12024 ': float(row['']),
                        'Paid_up_Capital_YE2021 ': float(row['']),
                        'Paid_up_Capital_YE2022 ': float(row['']),
                        'Paid_up_Capital_YE2023 ': float(row['']),
                        'Paid_up_Capital_Q12023 ': float(row['']),
                        'Paid_up_Capital_Q12024 ': float(row['']),
                        'Premium_Share_Capital_YE2021 ': float(row['']),
                        'Premium_Share_Capital_YE2022 ': float(row['']),
                        'Premium_Share_Capital_YE2023 ': float(row['']),
                        'Premium_Share_Capital_Q12023 ': float(row['']),
                        'Premium_Share_Capital_Q12024 ': float(row['']),
                        'Retained_Earnings_YE2021 ': float(row['']),
                        'Retained_Earnings_YE2022 ': float(row['']),
                        'Retained_Earnings_YE2023 ': float(row['']),
                        'Retained_Earnings_Q12023 ': float(row['']),
                        'Retained_Earnings_Q12024 ': float(row['']),
                        'Treasury_Stock_YE2021 ': float(row['']),
                        'Treasury_Stock_YE2022 ': float(row['']),
                        'Treasury_Stock_YE2023 ': float(row['']),
                        'Treasury_Stock_Q12023 ': float(row['']),
                        'Treasury_Stock_Q12024 ': float(row['']),
                        'Share_Company_Subsidiaries_YE2021 ': float(row['']),
                        'Share_Company_Subsidiaries_YE2022 ': float(row['']),
                        'Share_Company_Subsidiaries_YE2023 ': float(row['']),
                        'Share_Company_Subsidiaries_Q12023 ': float(row['']),
                        'Share_Company_Subsidiaries_Q12024 ': float(row['']),
                        'Other_Component_Equity_YE2021 ': float(row['']),
                        'Other_Component_Equity_YE2022 ': float(row['']),
                        'Other_Component_Equity_YE2023 ': float(row['']),
                        'Other_Component_Equity_Q12023 ': float(row['']),
                        'Other_Component_Equity_Q12024 ': float(row['']),
                        'Surplus_YE2021 ': float(row['']),
                        'Surplus_YE2022 ': float(row['']),
                        'Surplus_YE2023 ': float(row['']),
                        'Surplus_Q12023 ': float(row['']),
                        'Surplus_Q12024 ': float(row['']),
                        'Shareholders_Equity_YE2021 ': float(row['']),
                        'Shareholders_Equity_YE2022 ': float(row['']),
                        'Shareholders_Equity_YE2023 ': float(row['']),
                        'Shareholders_Equity_Q12023 ': float(row['']),
                        'Shareholders_Equity_Q12024 ': float(row['']),
                        'Minority_Interest_YE2021 ': float(row['']),
                        'Minority_Interest_YE2022 ': float(row['']),
                        'Minority_Interest_YE2023 ': float(row['']),
                        'Minority_Interest_Q12023 ': float(row['']),
                        'Minority_Interest_Q12024 ': float(row['']),
                        'Revenue_From_Operations_YE2021 ': float(row['']),
                        'Revenue_From_Operations_YE2022 ': float(row['']),
                        'Revenue_From_Operations_YE2023 ': float(row['']),
                        'Revenue_From_Operations_Q12023 ': float(row['']),
                        'Revenue_From_Operations_Q12024 ': float(row['']),
                        'Other_Income_YE2021 ': float(row['']),
                        'Other_Income_YE2022 ': float(row['']),
                        'Other_Income_YE2023 ': float(row['']),
                        'Other_Income_Q12023 ': float(row['']),
                        'Other_Income_Q12024 ': float(row['']),
                        'Total_Revenues_YE2021 ': float(row['']),
                        'Total_Revenues_YE2022 ': float(row['']),
                        'Total_Revenues_YE2023 ': float(row['']),
                        'Total_Revenues_Q12023 ': float(row['']),
                        'Total_Revenues_Q12024 ': float(row['']),
                        'Costs_YE2021 ': float(row['']),
                        'Costs_YE2022 ': float(row['']),
                        'Costs_YE2023 ': float(row['']),
                        'Costs_Q12023 ': float(row['']),
                        'Costs_Q12024 ': float(row['']),
                        'Sell_Administrative_Expenses_YE2021 ': float(row['']),
                        'Sell_Administrative_Expenses_YE2022 ': float(row['']),
                        'Sell_Administrative_Expenses_YE2023 ': float(row['']),
                        'Sell_Administrative_Expenses_Q12023 ': float(row['']),
                        'Sell_Administrative_Expenses_Q12024 ': float(row['']),
                        'Total_Cost_Expenses_YE2021 ': float(row['']),
                        'Total_Cost_Expenses_YE2022 ': float(row['']),
                        'Total_Cost_Expenses_YE2023 ': float(row['']),
                        'Total_Cost_Expenses_Q12023 ': float(row['']),
                        'Total_Cost_Expenses_Q12024 ': float(row['']),
                        'EBITDA_YE2021 ': float(row['']),
                        'EBITDA_YE2022 ': float(row['']),
                        'EBITDA_YE2023 ': float(row['']),
                        'EBITDA_Q12023 ': float(row['']),
                        'EBITDA_Q12024 ': float(row['']),
                        'Depre_Amor_YE2021 ': float(row['']),
                        'Depre_Amor_YE2022 ': float(row['']),
                        'Depre_Amor_YE2023 ': float(row['']),
                        'Depre_Amor_Q12023 ': float(row['']),
                        'Depre_Amor_Q12024 ': float(row['']),
                        'EBIT_YE2021 ': float(row['']),
                        'EBIT_YE2022 ': float(row['']),
                        'EBIT_YE2023 ': float(row['']),
                        'EBIT_Q12023 ': float(row['']),
                        'EBIT_Q12024 ': float(row['']),
                        'Net_Profit_YE2021 ': float(row['']),
                        'Net_Profit_YE2022 ': float(row['']),
                        'Net_Profit_YE2023 ': float(row['']),
                        'Net_Profit_Q12023 ': float(row['']),
                        'Net_Profit_Q12024 ': float(row['']),
                        'EPS_YE2021 ': float(row['']),
                        'EPS_YE2022 ': float(row['']),
                        'EPS_YE2023 ': float(row['']),
                        'EPS_Q12023 ': float(row['']),
                        'EPS_Q12024 ': float(row['']),
                        'Operating_Cash_Flow_YE2021 ': float(row['']),
                        'Operating_Cash_Flow_YE2022 ': float(row['']),
                        'Operating_Cash_Flow_YE2023 ': float(row['']),
                        'Operating_Cash_Flow_Q12023 ': float(row['']),
                        'Operating_Cash_Flow_Q12024 ': float(row['']),
                        'Investing_Cash_Flow_YE2021 ': float(row['']),
                        'Investing_Cash_Flow_YE2022 ': float(row['']),
                        'Investing_Cash_Flow_YE2023 ': float(row['']),
                        'Investing_Cash_Flow_Q12023 ': float(row['']),
                        'Investing_Cash_Flow_Q12024 ': float(row['']),
                        'Financing_Cash_Flow_YE2021 ': float(row['']),
                        'Financing_Cash_Flow_YE2022 ': float(row['']),
                        'Financing_Cash_Flow_YE2023 ': float(row['']),
                        'Financing_Cash_Flow_Q12023 ': float(row['']),
                        'Financing_Cash_Flow_Q12024 ': float(row['']),
                        'Net_Cash_Flow_YE2021 ': float(row['']),
                        'Net_Cash_Flow_YE2022 ': float(row['']),
                        'Net_Cash_Flow_YE2023 ': float(row['']),
                        'Net_Cash_Flow_Q12023 ': float(row['']),
                        'Net_Cash_Flow_Q12024 ': float(row['']),
                        'Current_Ratio_YE2022 ': float(row['']),
                        'Current_Ratio_YE2023 ': float(row['']),
                        'Current_Ratio_Q12023 ': float(row['']),
                        'Current_Ratio_Q12024 ': float(row['']),
                        'ROE_YE2022 ': float(row['']),
                        'ROE_YE2023 ': float(row['']),
                        'ROE_Q12023 ': float(row['']),
                        'ROE_Q12024 ': float(row['']),
                        'ROA_YE2022 ': float(row['']),
                        'ROA_YE2023 ': float(row['']),
                        'ROA_Q12023 ': float(row['']),
                        'ROA_Q12024 ': float(row['']),
                        'D_E_YE2022 ': float(row['']),
                        'D_E_YE2023 ': float(row['']),
                        'D_E_Q12023 ': float(row['']),
                        'D_E_Q12024 ': float(row['']),
                        'Total_Assets_Turnover_YE2022 ': float(row['']),
                        'Total_Assets_Turnover_YE2023 ': float(row['']),
                        'Total_Assets_Turnover_Q12023 ': float(row['']),
                        'Total_Assets_Turnover_Q12024 ': float(row['']),
                        'Gross_Profit_Margin_YE2022 ': float(row['']),
                        'Gross_Profit_Margin_YE2023 ': float(row['']),
                        'Gross_Profit_Margin_Q12023 ': float(row['']),
                        'Gross_Profit_Margin_Q12024 ': float(row['']),
                        'EBIT_Margin_YE2022 ': float(row['']),
                        'EBIT_Margin_YE2023 ': float(row['']),
                        'EBIT_Margin_Q12023 ': float(row['']),
                        'EBIT_Margin_Q12024 ': float(row['']),
                        'Net_Profit_Margin_YE2022 ': float(row['']),
                        'Net_Profit_Margin_YE2023 ': float(row['']),
                        'Net_Profit_Margin_Q12023 ': float(row['']),
                        'Net_Profit_Margin_Q12024 ': float(row['']),
                        'Sales_Growth_YE2022 ': float(row['']),
                        'Sales_Growth_YE2023 ': float(row['']),
                        'Sales_Growth_Q12023 ': float(row['']),
                        'Sales_Growth_Q12024 ': float(row['']),
                        'COGs_Growth_YE2022 ': float(row['']),
                        'COGs_Growth_YE2023 ': float(row['']),
                        'COGs_Growth_Q12023 ': float(row['']),
                        'COGs_Growth_Q12024 ': float(row['']),
                        'Total_Revenue_Growth_YE2022 ': float(row['']),
                        'Total_Revenue_Growth_YE2023 ': float(row['']),
                        'Total_Revenue_Growth_Q12023 ': float(row['']),
                        'Total_Revenue_Growth_Q12024 ': float(row['']),
                        'Total_Expense_Growth_YE2022 ': float(row['']),
                        'Total_Expense_Growth_YE2023 ': float(row['']),
                        'Total_Expense_Growth_Q12023 ': float(row['']),
                        'Total_Expense_Growth_Q12024 ': float(row['']),
                        'Net_Profit_Growth_YE2022 ': float(row['']),
                        'Net_Profit_Growth_YE2023 ': float(row['']),
                        'Net_Profit_Growth_Q12023 ': float(row['']),
                        'Net_Profit_Growth_Q12024 ': float(row['']),
                        'A_R_Turnover_Times_YE2022 ': float(row['']),
                        'A_R_Turnover_Times_YE2023 ': float(row['']),
                        'A_R_Turnover_Times_Q12023 ': float(row['']),
                        'A_R_Turnover_Times_Q12024 ': float(row['']),
                        'Avg_Collection_Period_Days_YE2022 ': float(row['']),
                        'Avg_Collection_Period_Days_YE2023 ': float(row['']),
                        'Avg_Collection_Period_Days_Q12023 ': float(row['']),
                        'Avg_Collection_Period_Days_Q12024 ': float(row['']),
                        'Inventory_Turnover_Times_YE2022 ': float(row['']),
                        'Inventory_Turnover_Times_YE2023 ': float(row['']),
                        'Inventory_Turnover_Times_Q12023 ': float(row['']),
                        'Inventory_Turnover_Times_Q12024 ': float(row['']),
                        'Avg_Inventory_Period_Days_YE2022 ': float(row['']),
                        'Avg_Inventory_Period_Days_YE2023 ': float(row['']),
                        'Avg_Inventory_Period_Days_Q12023 ': float(row['']),
                        'Avg_Inventory_Period_Days_Q12024 ': float(row['']),
                        'A_P_Turnover_Times_YE2022 ': float(row['']),
                        'A_P_Turnover_Times_YE2023 ': float(row['']),
                        'A_P_Turnover_Times_Q12023 ': float(row['']),
                        'A_P_Turnover_Times_Q12024 ': float(row['']),
                        'Avg_Payment_Period_Days_YE2022 ': float(row['']),
                        'Avg_Payment_Period_Days_YE2023 ': float(row['']),
                        'Avg_Payment_Period_Days_Q12023 ': float(row['']),
                        'Avg_Payment_Period_Days_Q12024 ': float(row['']),
                        'Cash_Cycle_Days_YE2022 ': float(row['']),
                        'Cash_Cycle_Days_YE2023 ': float(row['']),
                        'Cash_Cycle_Days_Q12023 ': float(row['']),
                        'Cash_Cycle_Days_Q12024 ': float(row['']),
                    }
                )
            
            messages.success(request, "CSV file has been uploaded and data inserted successfully.")
            return redirect('stock_list')
    else:
        form = CSVUploadForm()

    return render(request, 'stocks/upload_csv.html', {'form': form})

