# Generated by Django 5.0.7 on 2024-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockcsv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockCSV',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ebitda',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='pbv',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='pe',
        ),
        migrations.AddField(
            model_name='stock',
            name='de_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='pbv_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='pe_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='aa', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ev',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ev_ebitda',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='roa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='roe',
            field=models.FloatField(default=0),
        ),
    ]
