# Generated by Django 5.0.7 on 2024-07-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_delete_stockcsv_remove_stock_ebitda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='a', max_length=10),
        ),
    ]
