# Generated by Django 5.0.7 on 2024-07-31 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stock_a_p_net_q12023_stock_a_p_net_q12024_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='symbol',
            new_name='Symbol',
        ),
    ]
