# Generated by Django 5.0.7 on 2024-07-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_rename_symbol_stock_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Paid_up',
            field=models.FloatField(db_column='Paid_up', default=0),
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='Paid_up',
            new_name='paid_up',
        ),
        migrations.AlterField(
            model_name='stock',
            name='Symbol',
            field=models.CharField(db_column='Symbol', default='a', max_length=10),
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='Symbol',
            new_name='symbol',
        ),
    ]
