# Generated by Django 5.0.7 on 2024-08-01 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alter_stock_paid_up_rename_paid_up_stock_paid_up_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
